[theme]
base = "dark"
primaryColor = "#36d99b"
backgroundColor = "#071313"
secondaryBackgroundColor = "#102422"
textColor = "#edf8f3"
font = "sans serif"

[server]
maxUploadSize = 5
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
